### PR TITLE
Development

### PR DESCRIPTION
**Pull request by nicomness**

### CODE REVIEW

**Comment by k1r0s** [comment]
would you please include a folder with a working sample with the implementation of the client connected with a sandbox container <3

**Comment by k1r0s** [comment]
> would you please include a folder with a working sample with the implementation of the client connected with a sandbox container <3

that folder must be later removed before merge

**Comment by k1r0s** [comment]
maybe something like https://github.com/Einabit/client.java/tree/alpha

**Comment by nicomness** [comment]
Created a separate [PR](https://github.com/Einabit/client.java/pull/2) with a working example, in case you are happy with it you can just decline that PR and accept the changes coming from development branch.

**Comment by k1r0s** [comment]
I've cloned your fork, run the example but there is no output.

- clone
- docker compose up -d

then
docker logs <what_ever_docker_image_id>

**Comment by k1r0s** [comment]
please share the steps that you did in order to run it.

**Pull request merged**
